Fix color definitions and add Makefile
Hyprhook/Hyprhook pull request #9
Opened 2024-12-24 14:49 UTC by avih7531

This issue fixes https://github.com/Hyprhook/Hyprhook/issues/8 causes the plugin not to compile and also adds a _much_ needed Makefile

2024-12-31 21:56 UTC, Moerliy requested changes
the Makefile isn't needed. 
If you want to `make all` you need to cd into the hyprhook dir inside the project. 
It is a bit counterintuitive. We used the [hyprland-plugin](https://github.com/hyprwm/hyprland-plugins/tree/main) as a reference and there they separated into multiple different plugins. It's a bit weird and we should probably change it in the future, but having two Makefiles that do the exact same thing is a bit strange too.
@Yusuf-Duran what's your stance on this?

If you could clean up the commit message, it would be much appreciated or we could do a squash commit.

2024-12-31 21:56 UTC, Moerliy commented on hyprhook/src/main.cpp
> +#include <hyprland/src/helpers/Timer.hpp>
What's the reason behind timing being included or is this remanence code from trying stuff out?

2025-01-02 00:36 UTC, avih7531 commented on hyprhook/src/main.cpp
> +#include <hyprland/src/helpers/Timer.hpp>
Waiting on Hyprland to add it into the next version. That's a crappy fix but it works until they update

2025-01-02 00:38 UTC, Moerliy commented on hyprhook/src/main.cpp
> +#include <hyprland/src/helpers/Timer.hpp>
I see. I mean then it can stay in and go into main. It doesn't break anything and would only be deadweight code afterwards

2025-01-02 00:40 UTC, avih7531 commented on hyprhook/src/main.cpp
> +#include <hyprland/src/helpers/Timer.hpp>
:)

2025-01-06 02:54 UTC, avih7531 commented
Just trying to clean up these commits:

- Ignore 's'
- First 'fix Hyprland notification colors causing plugin not to compile' takes care of the breaking change in which `CColors` where changed into `CHyprColors`.  
  - It also includes a timer header in `main.cpp` from Hyprland in which is needed to compile the plugin -- I opened a pull in Hyprland which has been merged so as of the next release it can be removed or kept as deadweight code
  - (https://github.com/Hyprhook/Hyprhook/issues/8)
- Second 'fix Hyprland notification colors causing plugin not to compile' is the Makefile (sorry for the crappy commits, still getting used to git)
- 'fix monitor segfaults' updates `parseMonitor` in `Parser.cpp` to use `PHLMONITOR` instead of `CMonitor*` 
  - (https://github.com/Hyprhook/Hyprhook/issues/7)

2025-01-10 13:58 UTC, Yusuf-Duran commented on hyprhook/src/main.cpp
> +#include <hyprland/src/helpers/Timer.hpp>
in all honesty, given the repo only has one repo we don't really need the structure hyprland-plugins has suporting multiple plugins in one repo. We def need to clean that up.

2025-01-10 14:00 UTC, Yusuf-Duran commented
First of all, sorry for taking so long to really respond. Got too busy and forgot time. @Moerliy this honestly looks fine to me with some changes and stuff we should probably have done from the get-go.  This looks fine to me. In case your request got fixed, feel free to merge as long as @avih7531 says his PR is ready.

2025-01-10 14:04 UTC, Yusuf-Duran commented
I also added the other Issue aswell to the list of issues getting closed once this gets merged since this seems to fix it aswell if I see correctly.

2025-01-10 19:22 UTC, Moerliy commented
Let's get this in. Thanks for the fixes. Much appreciated

2025-01-10 19:22 UTC, merged